# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7db69b46c730e980a7d6dbc30f80b9a19bc6532a41591833b32f786af739c863b63456a0d100585b021da3da6fae2645032d1bdb3fc9b164ce9c62a23efa3af

test:
  secret_key_base: 446dd6f228855e12f4862fc9ff4ba9bde82d756827debe0bd26b9930776c05c42352e3ea1d8d2cbff13afdc981242dd50e76b4bb0370e8666918288416d122c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
